name: Extract and Deploy Comments

on:
  schedule:
    - cron: "18 22 * * *"  # Programa automático diario
  workflow_dispatch:        # Ejecución manual

jobs:
  extract_and_deploy:
    name: Extract Comments and Deploy to GitHub Pages
    runs-on: ubuntu-24.04

    steps:
      # 1. Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      # 3. Instalar dependencias
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Ejecutar script y generar comments.json
      - name: Run script to extract comments
        run: python extract_comments.py

      # 5. Mover comments.json al directorio docs
      - name: Move comments.json to docs folder
        run: |
          mkdir -p docs
          mv comments.json docs/

      # 6. Configurar credenciales para push manual
      - name: Configure Git
        run: |
          git config --global user.email "tu-correo@ejemplo.com"
          git config --global user.name "TuNombreDeUsuario"

      # 7. Hacer commit y push manualmente con tu token
      - name: Commit and Push Changes
        env:
          TOKEN: ${{ secrets.comments_steam }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git add docs/comments.json
          git commit -m "Update comments.json [skip ci]" || echo "No changes to commit"
          git push origin main
