name: extract comments

on:
  schedule:
    - cron: "18 22 * * *"
  workflow_dispatch:
    inputs:
      url:
        description: 'URL de Steam Community'
        required: false

jobs:
  run_script:
    name: Ejecutar script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      # Resto del flujo de trabajo, incluyendo la generación de artifacts y el archivo index.html

      - name: Guardar index.html como artefacto
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: index_html
          path: $GITHUB_WORKSPACE/index.html

      - name: Obtener información de los artifacts
        id: artifacts_info
        run: |
          echo "::set-output name=artifact_url::$(curl -s -H 'Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/actions/artifacts | jq -r '.artifacts[0].archive_download_url')"

  deploy_pages:
    name: Desplegar en GitHub Pages
    runs-on: ubuntu-latest
    needs: run_script
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Descargar index.html
        uses: actions/download-artifact@v2
        with:
          name: index_html
          path: $GITHUB_WORKSPACE

      - name: Obtener URL del último artifact
        id: get_artifact_url
        run: |
          artifact_url=$(curl -s -H 'Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/actions/artifacts | jq -r '.artifacts[0].archive_download_url')
          echo "::set-output name=artifact_url::$artifact_url"

      - name: Actualizar enlace al último artifact en index.html
        run: sed -i "s|/path/to/last_artifact|$GITHUB_WORKSPACE/$(cat ${{ steps.get_artifact_url.outputs.artifact_url }} | awk -F/ '{print $NF}')|g" $GITHUB_WORKSPACE/index.html

      - name: Desplegar en GitHub Pages
        run: |
          cd $GITHUB_WORKSPACE
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Actualizar enlace al último artifact"
          git push origin main
