name: extract comments

on:
  schedule:
    - cron: "18 22 * * *"
  workflow_dispatch:
    inputs:
      url:
        description: 'URL de Steam Community'
        required: false

jobs:
  run_script:
    name: Ejecutar script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      # Resto del flujo de trabajo, incluyendo la generación de artifacts y el archivo index.html

      - name: Guardar index.html como artefacto
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: index_html
          path: $GITHUB_WORKSPACE/index.html

  deploy_pages:
    name: Desplegar en GitHub Pages
    runs-on: ubuntu-latest
    needs: run_script
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Restaurar index.html como artifact
        uses: actions/download-artifact@v2
        with:
          name: index_html
          path: $GITHUB_WORKSPACE

      - name: Desplegar en GitHub Pages
        run: |
          mv $GITHUB_WORKSPACE/index.html $GITHUB_WORKSPACE/path/to/last_artifact
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add path/to/last_artifact
          git commit -m "Actualizar enlace al último artifact"
          git push origin main
