name: extract comments

on:
  schedule:
    - cron: "18 22 * * *"
  workflow_dispatch:

jobs:
  run_script:
    name: Ejecutar script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Cambia a la versión de Python que necesites

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script y guardar archivo comments.json
        run: python extract_comments.py

      - name: Crear directorio de artefacto
        run: mkdir artifacts

      - name: Mover comments.json al directorio de artefacto
        run: mv comments.json artifacts/

      - name: Guardar directorio como artefacto
        if: always()  # This ensures that the step runs even if the previous step fails
        uses: actions/upload-artifact@v2
        with:
          name: comments
          path: artifacts/
